import './globals.css'
import Link from 'next/link';
import { headers } from 'next/headers';

export const metadata = {
  title: 'Instagram Clone',
  description: 'Generated by Next.js',
  viewport: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no',
}

function BottomNav() {
  return (
    <div style={{
      position: 'fixed',
      bottom: 0,
      left: 0,
      right: 0,
      width: '100%',
      background: '#000',
      borderTop: '1px solid #222',
      display: 'flex',
      justifyContent: 'space-around',
      alignItems: 'center',
      padding: '12px 0',
      zIndex: 1000,
    }}>
      <Link href="/" style={{ color: '#fff', fontSize: '24px', textDecoration: 'none' }}>🏠</Link>
      <Link href="/explore" style={{ color: '#fff', fontSize: '24px', textDecoration: 'none' }}>🔍</Link>
      <Link href="/create" style={{ color: '#fff', fontSize: '24px', textDecoration: 'none' }}>➕</Link>
      <Link href="/profile" style={{ color: '#fff', fontSize: '24px', textDecoration: 'none' }}>👤</Link>
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ background: '#000', color: '#fff', margin: 0, paddingBottom: '60px', display: 'flex', flexDirection: 'column', alignItems: 'center', touchAction: 'manipulation' }}>
        <div style={{ width: '100%', maxWidth: '400px', overflowX: 'hidden' }}>
          {children}
        </div>
        <BottomNav />
      </body>
    </html>
  )
}
